# Copyright (c) 2021 by xfangfang. All Rights Reserved.


name: Build Sinacast

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      ssh_darwin:
        description: 'SSH connection to Darwin'
        required: false
        default: 'false'
      ssh_ubuntu:
        description: 'SSH connection to Ubuntu'
        required: false
        default: 'false'
      release:
        description: 'Push a new release'
        required: false
        default: 'false'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.info.outputs.version }}
      standard_version: ${{ steps.info.outputs.standard_version }}
      DIST_DMG: ${{ steps.info.outputs.DIST_DMG }}
      DIST_DMG_ARM: ${{ steps.info.outputs.DIST_DMG_ARM }}
      DIST_EXE: ${{ steps.info.outputs.DIST_EXE }}
      DIST_EXE_DEBUG: ${{ steps.info.outputs.DIST_EXE_DEBUG }}
      DIST_EXE32: ${{ steps.info.outputs.DIST_EXE32 }}
      DIST_EXE32_DEBUG: ${{ steps.info.outputs.DIST_EXE32_DEBUG }}
      DIST_AMD64: ${{ steps.info.outputs.DIST_AMD64 }}
      DIST_AMD64_DEB: ${{ steps.info.outputs.DIST_AMD64_DEB }}
      DIST_ARMV7: ${{ steps.info.outputs.DIST_ARMV7 }}
      DIST_ARMV7_DEB: ${{ steps.info.outputs.DIST_ARMV7_DEB }}
      DIST_ARMV8: ${{ steps.info.outputs.DIST_ARMV8 }}
      DIST_ARMV8_DEB: ${{ steps.info.outputs.DIST_ARMV8_DEB }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug version
        run: |
          export VERSION=`git rev-parse --short HEAD`
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Release version
        if: github.event.inputs.release == 'true' && github.event.inputs.release != 'false' && !cancelled()
        run: |
          export VERSION=`python3 -c "exec(open('macast/__pkginfo__.py').read()); print(__version__)"`
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Version
        id: info
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          export STANDARD_VERSION=`python3 -c "exec(open('macast/__pkginfo__.py').read()); print(__version__)"`
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=standard_version::${STANDARD_VERSION}"
          echo "::set-output name=DIST_DMG::Sinacast-MacOS-${VERSION}-IntelChip.dmg"
          echo "::set-output name=DIST_DMG_ARM::Sinacast-MacOS-${VERSION}-AppleSilicon.dmg"
          echo "::set-output name=DIST_EXE::Sinacast-Windows-${VERSION}-x64.exe"
          echo "::set-output name=DIST_EXE_DEBUG::Sinacast-Windows-${VERSION}-x64-debug.exe"
          echo "::set-output name=DIST_EXE32::Sinacast-Windows-${VERSION}-x86.exe"
          echo "::set-output name=DIST_EXE32_DEBUG::Sinacast-Windows-${VERSION}-x86-debug.exe"
          echo "::set-output name=DIST_AMD64::Sinacast-Linux-${VERSION}-amd64"
          echo "::set-output name=DIST_AMD64_DEB::Sinacast-Linux-${VERSION}-amd64.deb"
          echo "::set-output name=DIST_ARMV7::Sinacast-Linux-${VERSION}-armv7"
          echo "::set-output name=DIST_ARMV7_DEB::Sinacast-Linux-${VERSION}-armv7.deb"
          echo "::set-output name=DIST_ARMV8::Sinacast-Linux-${VERSION}-armv8"
          echo "::set-output name=DIST_ARMV8_DEB::Sinacast-Linux-${VERSION}-armv8.deb"
          echo $VERSION
          echo $STANDARD_VERSION

  release:
    needs: [ build-win-x64, build-macos-apple, build-macos-intel, version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        if: github.event.inputs.release == 'true' && github.event.inputs.release != 'false' && !cancelled()

      - name: Version
        if: github.event.inputs.release == 'true' && github.event.inputs.release != 'false' && !cancelled()
        run: |
          echo "VERSION=${{ needs.version.outputs.version }}" >> $GITHUB_ENV
          echo "DIST_DMG=${{ needs.version.outputs.DIST_DMG }}" >> $GITHUB_ENV
          echo "DIST_DMG_ARM=${{ needs.version.outputs.DIST_DMG_ARM }}" >> $GITHUB_ENV
          echo "DIST_EXE=${{ needs.version.outputs.DIST_EXE }}" >> $GITHUB_ENV
          echo "DIST_EXE_DEBUG=${{ needs.version.outputs.DIST_EXE_DEBUG }}" >> $GITHUB_ENV
          echo "DIST_EXE32=${{ needs.version.outputs.DIST_EXE32 }}" >> $GITHUB_ENV
          echo "DIST_EXE32_DEBUG=${{ needs.version.outputs.DIST_EXE32_DEBUG }}" >> $GITHUB_ENV
          echo "DIST_AMD64=${{ needs.version.outputs.DIST_AMD64 }}" >> $GITHUB_ENV
          echo "DIST_AMD64_DEB=${{ needs.version.outputs.DIST_AMD64_DEB }}" >> $GITHUB_ENV
          echo "DIST_ARMV7=${{ needs.version.outputs.DIST_ARMV7 }}" >> $GITHUB_ENV
          echo "DIST_ARMV7_DEB=${{ needs.version.outputs.DIST_ARMV7_DEB }}" >> $GITHUB_ENV
          echo "DIST_ARMV8=${{ needs.version.outputs.DIST_ARMV8 }}" >> $GITHUB_ENV
          echo "DIST_ARMV8_DEB=${{ needs.version.outputs.DIST_ARMV8_DEB }}" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - name: Upload
        if: github.event.inputs.release == 'true' && github.event.inputs.release != 'false' && !cancelled()
        uses: ncipollo/release-action@v1
        with:
          name: Sinacast ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          omitBodyDuringUpdate: true
          body: This release is built by github-action.
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: >
            ${{ env.DIST_DMG }}/${{ env.DIST_DMG }},
            ${{ env.DIST_DMG_ARM }}/${{ env.DIST_DMG_ARM }},
            ${{ env.DIST_EXE }}/${{ env.DIST_EXE }},
            ${{ env.DIST_EXE_DEBUG }}/${{ env.DIST_EXE_DEBUG }},
            ${{ env.DIST_EXE32 }}/${{ env.DIST_EXE32 }},
            ${{ env.DIST_EXE32_DEBUG }}/${{ env.DIST_EXE32_DEBUG }},
            ${{ env.DIST_AMD64 }}/${{ env.DIST_AMD64 }},
            ${{ env.DIST_AMD64_DEB }}/${{ env.DIST_AMD64_DEB }},
            ${{ env.DIST_ARMV7 }}/${{ env.DIST_ARMV7 }},
            ${{ env.DIST_ARMV7_DEB }}/${{ env.DIST_ARMV7_DEB }},
            ${{ env.DIST_ARMV8 }}/${{ env.DIST_ARMV8 }},
            ${{ env.DIST_ARMV8_DEB }}/${{ env.DIST_ARMV8_DEB }}

  build-win-x64:
    needs: [ version ]
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Requirement
        run: |
          choco install upx
          pip3 install -r requirements.txt
          pip3 install pyinstaller
          $client = new-object System.Net.WebClient
          $client.DownloadFile('https://github.com/xfangfang/Macast/releases/download/v0.1/mpv-0.34.0-x86_64.7z','mpv.7z')
          7z x -obin mpv.7z *.exe

      - name: Build
        id: compile
        run: |
          $VERSION="${{ needs.version.outputs.version }}"
          $DIST_EXE_DEBUG="${{ needs.version.outputs.DIST_EXE_DEBUG }}"
          $DIST_EXE="${{ needs.version.outputs.DIST_EXE }}"
          echo ${VERSION} ${DIST_EXE}
          python3 setup.py compile_catalog -f -D macast -d macast\i18n
          $BUILD_LANG=(ls macast\i18n | ForEach-Object {echo --add-data="macast\i18n\$($_.Name)\LC_MESSAGES\*.mo;macast\i18n\$($_.Name)\LC_MESSAGES"})
          $BUILD_ASSETS_1=(ls macast\assets | ?{$_.PsIsContainer -eq $true} | ForEach-Object {echo --add-data="macast\assets\$($_.Name)\*;macast\assets\$($_.Name)"})
          $BUILD_ASSETS_2=("--add-data=macast\assets\*;macast\assets","--add-data=macast\xml\*;macast\xml","--add-binary=bin\mpv.exe;bin")
          $BUILD_HIDDEN_IMPORT=("--hidden-import=win32process","--hidden-import=win32gui")
          $BUILD_OTHERS=("--additional-hooks-dir=.","--icon=macast\assets\icon.ico","--runtime-tmpdir=%Temp%\Sinacast", "--upx-exclude=mpv.exe")
          $BUILD_COMMON=($BUILD_LANG+$BUILD_ASSETS_1+$BUILD_ASSETS_2+$BUILD_HIDDEN_IMPORT+$BUILD_OTHERS)
          pyinstaller --noconfirm -F -w  $BUILD_COMMON --splash=macast\assets\macast_splash.jpg Sinacast.py
          cp dist\Sinacast.exe $DIST_EXE
          pyinstaller --noconfirm -F -d=all $BUILD_COMMON Sinacast.py
          cp dist\Sinacast.exe $DIST_EXE_DEBUG
          echo "::set-output name=status::success"

      - name: Upload dist
        uses: actions/upload-artifact@v2
        if: steps.compile.outputs.status == 'success'
        with:
          name: ${{ needs.version.outputs.DIST_EXE }}
          path: ${{ needs.version.outputs.DIST_EXE }}

      - name: Upload dist debug
        uses: actions/upload-artifact@v2
        if: steps.compile.outputs.status == 'success'
        with:
          name: ${{ needs.version.outputs.DIST_EXE_DEBUG }}
          path: ${{ needs.version.outputs.DIST_EXE_DEBUG }}

  build-macos-intel:
    needs: [ version ]
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install create-dmg
        run: brew install create-dmg

      - name: install universal python
        run: |
          wget https://www.python.org/ftp/python/3.9.8/python-3.9.8-macos11.pkg
          sudo installer -pkg python-3.9.8-macos11.pkg -target /

      - name: Install Requirement
        run: |
          pip3 install -r requirements.txt
          pip3 install py2app
          wget https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-latest.tar.gz
          mkdir -p bin && tar --strip-components 2 -C bin -xzvf mpv-latest.tar.gz mpv.app/Contents/MacOS

      - name: Readme
        run: |
          mkdir -p dist
          echo "Sinacast" > dist/readme.txt
          echo "" >> dist/readme.txt
          echo "if you see any of these after open this application:" >> dist/readme.txt
          echo "1: Sinacast.app is damaged and can't be opened. You should move it to he Trash." >> dist/readme.txt
          echo "2: Sinacast.app can't be opened because it is from an unidentified developer." >> dist/readme.txt
          echo "" >> dist/readme.txt
          echo "Please run this command in your terminal:" >> dist/readme.txt
          echo "sudo xattr -rd com.apple.quarantine /Applications/Sinacast.app" >> dist/readme.txt

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh_darwin == 'true' && github.event.inputs.ssh_darwin  != 'false') || contains(github.event.action, 'ssh_darwin')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Build
        id: compile
        env:
          VERSION: ${{ needs.version.outputs.version }}
          DIST_DMG: ${{ needs.version.outputs.DIST_DMG }}
        run: |
          echo $VERSION $DIST_DMG
          python3 setup.py compile_catalog -f -D macast -d macast/i18n
          python3 setup_py2app.py py2app --arch=x86_64
          cp -R bin dist/Sinacast.app/Contents/Resources/
          create-dmg --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "Sinacast.app" 200 190  --icon "readme.txt" 400 100 --hide-extension "Sinacast.app" --app-drop-link 600 185  --volname "Sinacast-v${VERSION} Installer" ${DIST_DMG} "dist/"
          echo "::set-output name=status::success"

      - name: Upload dist
        uses: actions/upload-artifact@v2
        if: steps.compile.outputs.status == 'success'
        with:
          name: ${{ needs.version.outputs.DIST_DMG }}
          path: ${{ needs.version.outputs.DIST_DMG }}

  build-macos-apple:
    needs: [ version ]
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install create-dmg
        run: brew install create-dmg

      - name: install universal python
        run: |
          wget https://www.python.org/ftp/python/3.9.8/python-3.9.8-macos11.pkg
          sudo installer -pkg python-3.9.8-macos11.pkg -target /

      - name: Install Requirement
        run: |
          pip3 install -r requirements.txt
          pip3 install py2app
          wget https://github.com/xfangfang/Macast/releases/download/v0.1/mpv-0.34.1-darwin-arm.tar.gz
          mkdir -p bin_arm && tar --strip-components 2 -C bin_arm -xzvf mpv-0.34.1-darwin-arm.tar.gz mpv.app/Contents/MacOS
          wget https://github.com/xfangfang/Macast/releases/download/v0.1/macos_arm_lxml_netifaces.tar.gz

      - name: Readme
        run: |
          mkdir -p dist
          echo "Sinacast" > dist/readme.txt
          echo "" >> dist/readme.txt
          echo "if you see any of these after open this application:" >> dist/readme.txt
          echo "1: Sinacast.app is damaged and can't be opened. You should move it to he Trash." >> dist/readme.txt
          echo "2: Sinacast.app can't be opened because it is from an unidentified developer." >> dist/readme.txt
          echo "" >> dist/readme.txt
          echo "Please run this command in your terminal:" >> dist/readme.txt
          echo "sudo xattr -rd com.apple.quarantine /Applications/Sinacast.app" >> dist/readme.txt

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh_darwin == 'true' && github.event.inputs.ssh_darwin  != 'false') || contains(github.event.action, 'ssh_darwin')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Build arm
        id: compile_arm
        env:
          VERSION: ${{ needs.version.outputs.version }}
          DIST_DMG_ARM: ${{ needs.version.outputs.DIST_DMG_ARM }}
        run: |
          echo $VERSION $DIST_DMG_ARM
          python3 setup.py compile_catalog -f -D macast -d macast/i18n
          python3 setup_py2app.py py2app --arch=arm64
          cp -R bin_arm dist/Sinacast.app/Contents/Resources/bin
          tar --strip-components 1 -C dist/Sinacast.app/Contents/Resources/lib/python3.9/lib-dynload -xzvf macos_arm_lxml_netifaces.tar.gz
          create-dmg --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "Sinacast.app" 200 190  --icon "readme.txt" 400 100 --hide-extension "Sinacast.app" --app-drop-link 600 185  --volname "Sinacast-v${VERSION} Installer" ${DIST_DMG_ARM} "dist/"
          echo "::set-output name=status::success"

      - name: Upload dist arm
        uses: actions/upload-artifact@v2
        if: steps.compile_arm.outputs.status == 'success'
        with:
          name: ${{ needs.version.outputs.DIST_DMG_ARM }}
          path: ${{ needs.version.outputs.DIST_DMG_ARM }}